config/routes.rb
Rails.application.routes.draw do

  root 'kittens#index'
  get 'kitten/new',         to: 'kittens#new'
  post 'kittens',           to: 'kittens#create'
  get 'kittens/:id',        to: 'kittens#show',     as: 'kitten'
  get 'kittens',            to: 'kittens#index'
  get 'kittens/:id/edit',   to: 'kittens#edit',     as: 'kitten_edit'
  delete 'kittens/:id',     to: 'kittens#destroy'
  put 'kittens/:id',        to: 'kittens#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten created successfully"
      redirect_to @kitten
    else
      redirect_to 'new'
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
      end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    Kitten.find(params[:id]).destroy
    flash[:success] = "Kitten deleted successfully"
    redirect_to root_url
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update_attributes(kitten_params)
    flash[:success] = "Kitten edited successfully"
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :softness, :cuteness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<li>
  <ul class="kitten">
    <li>Name: <%= kitten.name %></li>
    <li>Age: <%= kitten.age %></li>
    <li>Softness: <%= kitten.softness %></li>
    <li>Cuteness: <%= kitten.cuteness %></li>
    <li></li>
    <li><%= link_to "More detail on this kitten", kitten %></li>
    <li><%= link_to "Delete kitten", kitten, method: :delete %>
  </ul>
</li>

app/views/kittens/_kitten_form.html.erb
<%= form_for(:kitten, url: kittens_path) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :age, "Age (months)" %>
<%= f.select :age, options_for_select((1..12).to_a, @kitten.age) %>
<br>
<%= f.label :softness %>
<%= f.select :softness, options_for_select((1..10).to_a, @kitten.softness) %>
<br>
<%= f.label :cuteness %>
<%= f.select :cuteness, options_for_select((1..10).to_a, @kitten.cuteness) %>
<br>
<%= f.submit "Submit" %>

<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Kittens#edit</h1>
<p>Find me in app/views/kittens/edit.html.erb</p>

<%= render 'kitten_form' %>

<%= link_to "Show kitten", @kitten %> | 
<%= link_to "Delete kitten", @kitten, method: :delete %>

app/views/kittens/index.html.erb
<h1>Kittens#index</h1>
<p>Find me in app/views/kittens/index.html.erb</p>

<%= render @kittens %>

app/views/kittens/new.html.erb
<h1>Kittens#new</h1>
<p>Find me in app/views/kittens/new.html.erb</p>

<%= render 'kitten_form' %>

app/views/kittens/show.html.erb
<h1>Kittens#show</h1>
<p>Find me in app/views/kittens/show.html.erb</p>

<ul class="kitten">
  <li>Name: <%= @kitten.name %></li>
  <li>Age: <%= @kitten.age %></li>
  <li>Softness: <%= @kitten.softness %></li>
  <li>Cuteness: <%= @kitten.cuteness %></li>
</ul>
<br>
<%= link_to "Edit kitten", kitten_edit_path(@kitten) %> |
<%= link_to "Delete kitten", @kitten, method: :delete %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <%= link_to 'All kittens', root_url %> |
      <%= link_to 'New kitten', kitten_new_path %>

    <div>
      <div id="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-"<%= key %>"><%= value %></div>
          <% end %>
      </div>
    <%= yield %>
  </body>
</html>